// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SessionWrapper from "./SessionWrapper";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 👇 declaras la función como async
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 🚀 Obtener la sesión en el servidor
  const session = await getServerSession(authOptions);

  return (
    <html lang="es">
      <body
        
      >
        <Toaster position="top-right" />
        {/* 🚀 Pasar la sesión al cliente */}
        <SessionWrapper session={session}>{children}</SessionWrapper>
      </body>
    </html>
  );
}

